
name: ai-sgf-evcs
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - matplotlib=3.8.4
  - pyyaml=6.0.1
  - pip
  - pip:
      - pyarrow==16.1.0
